### ISSUE TITLE
About refinement network

### ISSUE THREAD

**Issue by harunakai** [XunpengYi/Diff-IF#11]
您好，这是非常棒的工作，但我有一个疑问，请问您尝试过没有refine，仅有ddpm将图像融合，并测试效果的做法吗。您的最终模型性能优于其他融合方法看起来似乎refinement network起了很大一部分作用，我很好奇在不refine时，模型的性能是怎样的。希望得到你的回复和解答，非常感谢！

**Comment by XunpengYi** [comment]
refinement network也是我们提出的一个方法组成部分，如果去掉refinement network，模型仅从分布上拟合目标搜索得到的融合最优分布，尽管分布上相似，但像素层面表现不佳。因此我们也建议在像素级别提供一个约束，以保证可视化效果。
