### ISSUE TITLE
已经有了融合好的图像，为什么还要用diffsion去生成？

### ISSUE THREAD

**Issue by saltyfish347** [XunpengYi/Diff-IF#4]
我有一个问题，这篇文章里引入“融合知识先验”，相当于用fusion_k作为groundtruth来训练模型，那么怎么保证这个模型生成出来的效果比其他模型生成的效果更好呢？

**Comment by XunpengYi** [comment]
Thank you for your attention. Firstly, the integration of fusion knowledge prior is only present in the training dataset, while the validation and test datasets do not contain any fusion image. Thus, the diffusion-based method can be employed to obtain them. Secondly, the fusion knowledge prior is not a single method but a collection of multiple state-of-the-art (SOTA) methods. Furthermore, the optimal sample is obtained through targeted search. The supervision is provided by the best sample among all methods, hence it is superior to the fusion results of any subset of methods.

**Comment by wuyi027** [comment]
Hello author, I have a similar question about this, whether the fusion result obtained by this model is similar to or higher than the optimal one in the fusion knowledge prior.

**Comment by XunpengYi** [comment]
The optimal result in the fusion knowledge prior is not achieved by a single method but represents the best performance of existing fusion methods in the current scenario. After the diffusion model learns the optimal fusion prior in various scenarios, it aggregates the advantages of different fusion methods while avoiding their disadvantages, making it foreseeable that it will surpass existing individual fusion methods. Of course, although it is possible, it does not necessarily mean that the diffusion model can surpass the sum of all methods (this involves the issue of generalization). For specifics, you can refer to the related theories of knowledge distillation.

**Comment by XunpengYi** [comment]
The optimal result in the fusion knowledge prior is not achieved by a single method but represents the best performance of existing fusion methods in the current scenario. After the diffusion model learns the optimal fusion prior in various scenarios, it aggregates the advantages of different fusion methods while avoiding their disadvantages, making it foreseeable that it will surpass existing individual fusion methods. Of course, although it is possible, it does not absolutely mean that the diffusion model can surpass the sum of all methods (this involves the issue of generalization). For specifics, you can refer to the related theories of knowledge distillation.
