### ISSUE TITLE
Test on M3FD dataset

### ISSUE THREAD

**Issue by Wei-1989** [XunpengYi/Diff-IF#8]
I conduct test on M3FD datasets with pretrained weight you provided, wheareas there seems a little issue with the outputs? the results are only gray images. Is there a problem with my operation? I have modifed "dataroot" in config file
I use this commond:
CUDA_VISIBLE_DEVICES=0 python infer_ddim.py  --config config/diff-if-ivf_val.json
![00011](https://github.com/user-attachments/assets/fd27cef7-900d-4847-8ff4-e8ced872db7f)

**Comment by XunpengYi** [comment]
You may have other mismatches, it is recommended that you check all the paths in the files to see if it matches. (including the images in the `Infrared` and `Visible` folders) This is very important. At the time they placed correctly, the correct result can be obtained.

**Comment by XunpengYi** [comment]
You may have other mismatches, it is recommended that you check all the paths in the files and see if it matches. (including the images in the Infrared and Visible folders) This is very important. At the time they are all placed correctly, the correct fusion result can be obtained.

**Comment by Wei-1989** [comment]
> You may have other mismatches, it is recommended that you check all the paths in the files and see if it matches. (including the images in the Infrared and Visible folders) This is very important. At the time they are all placed correctly, the correct fusion result can be obtained.

OK! I check again. It's my fault, sincerely sorry for bothering your time~
